name: flask
dependencies:
- flask=0.10.1=py35_1
- flask-login=0.2.11=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_0
- markupsafe=0.23=py35_0
- openssl=1.0.2d=0
- pip=7.1.2=py35_0
- python=3.5.0=1
- readline=6.2=2
- setuptools=18.5=py35_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- werkzeug=0.11.2=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - babel==2.1.1
  - blinker==1.4
  - coverage==4.0.3
  - decorator==4.0.4
  - defusedxml==0.4.1
  - flask-babel==0.9
  - flask-mail==0.9.1
  - flask-openid==1.2.5
  - flask-sqlalchemy==2.1
  - flask-whooshalchemy==0.56
  - flask-wtf==0.12
  - flipflop==1.0
  - guess-language==0.2
  - pbr==1.8.1
  - python3-openid==3.0.9
  - pytz==2015.7
  - six==1.10.0
  - speaklater==1.3
  - sqlalchemy==1.0.9
  - sqlalchemy-migrate==0.10.0
  - sqlparse==0.1.18
  - tempita==0.5.2
  - whoosh==2.7.0
  - wtforms==2.0.2
